# runs all dockers

services:
  
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus-server
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - system-monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    networks:
    - system-monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports: 
    - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
    - system-monitoring
    restart: unless-stopped

networks:
  system-monitoring:
    external: true
