# runs all dockers

version: '3.8'
services:
  
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - system-monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
    - system-monitoring
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - system-monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports: 
    - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=SuperPassword
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
    - system-monitoring
    restart: unless-stopped

networks:
  system-monitoring:
    external: true
