# prometheus configuration - tells prometheus to scrape data from Node Exporter every 15 seconds

global:
  scrape_interval: "15s" # change scrape interval if nedded

scrape_configs: 
    # scrapes prometheus servers data
  - job_name: 'prometheus-server'
    static_configs:
      - targets: ['prometheus-server:9090']

    # scrapes local hardware data
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']